language: bash
notifications:
    email: [matthew@baggett.me]
before_script:
    - 'docker login -u $DOCKER_LOGIN -p $DOCKER_PASSWORD $DOCKER_REGISTRY'
    - 'sudo rm /usr/local/bin/docker-compose'
    - 'curl -L https://github.com/docker/compose/releases/download/1.21.0/docker-compose-`uname -s`-`uname -m` > docker-compose'
    - 'chmod +x docker-compose'
    - 'sudo mv docker-compose /usr/local/bin'
script:
    - 'docker-compose -f build.yml build redis-$VERSION'
after_script:
    - 'docker-compose -f build.yml push redis-$VERSION'
env:
    - VERSION=5-alpine3.11
    - VERSION=5-alpine3.12
    - VERSION=5-alpine3.8
    - VERSION=5-alpine3.9
    - VERSION=5-buster
    - VERSION=5-stretch
    - VERSION=5.0
    - VERSION=5.0-32bit
    - VERSION=5.0-32bit-buster
    - VERSION=5.0-32bit-stretch
    - VERSION=5.0-alpine
    - VERSION=5.0-alpine3.10
    - VERSION=5.0-alpine3.11
    - VERSION=5.0-alpine3.12
    - VERSION=5.0-alpine3.8
    - VERSION=5.0-alpine3.9
    - VERSION=5.0-buster
    - VERSION=5.0-rc
    - VERSION=5.0-rc-32bit
    - VERSION=5.0-rc-32bit-stretch
    - VERSION=5.0-rc-alpine
    - VERSION=5.0-rc-alpine3.8
    - VERSION=5.0-rc-stretch
    - VERSION=5.0-rc3
    - VERSION=5.0-rc3-32bit
    - VERSION=5.0-rc3-32bit-stretch
    - VERSION=5.0-rc3-alpine
    - VERSION=5.0-rc3-alpine3.8
    - VERSION=5.0-rc3-stretch
    - VERSION=5.0-rc4
    - VERSION=5.0-rc4-32bit
    - VERSION=5.0-rc4-32bit-stretch
    - VERSION=5.0-rc4-alpine
    - VERSION=5.0-rc4-alpine3.8
    - VERSION=5.0-rc4-stretch
    - VERSION=5.0-rc5
    - VERSION=5.0-rc5-32bit
    - VERSION=5.0-rc5-32bit-stretch
    - VERSION=5.0-rc5-alpine
    - VERSION=5.0-rc5-alpine3.8
    - VERSION=5.0-rc5-stretch
    - VERSION=5.0-rc6
    - VERSION=5.0-rc6-32bit
    - VERSION=5.0-rc6-32bit-stretch
    - VERSION=5.0-rc6-alpine
    - VERSION=5.0-rc6-alpine3.8
    - VERSION=5.0-rc6-stretch
    - VERSION=5.0-stretch
    - VERSION=5.0.0
    - VERSION=5.0.0-32bit
    - VERSION=5.0.0-32bit-stretch
    - VERSION=5.0.0-alpine
    - VERSION=5.0.0-alpine3.8
    - VERSION=5.0.0-stretch
    - VERSION=5.0.1
    - VERSION=5.0.1-32bit
    - VERSION=5.0.1-32bit-stretch
    - VERSION=5.0.1-alpine
    - VERSION=5.0.1-alpine3.8
    - VERSION=5.0.1-stretch
    - VERSION=5.0.2
    - VERSION=5.0.2-32bit
    - VERSION=5.0.2-32bit-stretch
    - VERSION=5.0.2-alpine
    - VERSION=5.0.2-alpine3.8
    - VERSION=5.0.2-stretch
    - VERSION=5.0.3
    - VERSION=5.0.3-32bit
    - VERSION=5.0.3-32bit-stretch
    - VERSION=5.0.3-alpine
    - VERSION=5.0.3-alpine3.8
    - VERSION=5.0.3-alpine3.9
    - VERSION=5.0.3-stretch
    - VERSION=5.0.4
    - VERSION=5.0.4-32bit
    - VERSION=5.0.4-32bit-stretch
    - VERSION=5.0.4-alpine
    - VERSION=5.0.4-alpine3.9
    - VERSION=5.0.4-stretch
    - VERSION=5.0.5
    - VERSION=5.0.5-32bit
    - VERSION=5.0.5-32bit-buster
    - VERSION=5.0.5-32bit-stretch
    - VERSION=5.0.5-alpine
    - VERSION=5.0.5-alpine3.10
    - VERSION=5.0.5-alpine3.9
    - VERSION=5.0.5-buster
    - VERSION=5.0.5-stretch
    - VERSION=5.0.6
    - VERSION=5.0.6-32bit
    - VERSION=5.0.6-32bit-buster
    - VERSION=5.0.6-alpine
    - VERSION=5.0.6-alpine3.10
    - VERSION=5.0.6-buster
    - VERSION=5.0.7
    - VERSION=5.0.7-32bit
    - VERSION=5.0.7-32bit-buster
    - VERSION=5.0.7-alpine
    - VERSION=5.0.7-alpine3.10
    - VERSION=5.0.7-alpine3.11
    - VERSION=5.0.7-buster
    - VERSION=5.0.8
    - VERSION=5.0.8-32bit
    - VERSION=5.0.8-32bit-buster
    - VERSION=5.0.8-alpine
    - VERSION=5.0.8-alpine3.11
    - VERSION=5.0.8-buster
    - VERSION=5.0.9
    - VERSION=5.0.9-32bit
    - VERSION=5.0.9-32bit-buster
    - VERSION=5.0.9-alpine
    - VERSION=5.0.9-alpine3.11
    - VERSION=5.0.9-alpine3.12
    - VERSION=5.0.9-buster
    - VERSION=6
    - VERSION=6-alpine
    - VERSION=6-alpine3.11
    - VERSION=6-alpine3.12
    - VERSION=6-buster
    - VERSION=6.0
    - VERSION=6.0-alpine
    - VERSION=6.0-alpine3.11
    - VERSION=6.0-alpine3.12
    - VERSION=6.0-buster
    - VERSION=6.0-rc
    - VERSION=6.0-rc-32bit
    - VERSION=6.0-rc-32bit-buster
    - VERSION=6.0-rc-alpine
    - VERSION=6.0-rc-alpine3.11
    - VERSION=6.0-rc-buster
    - VERSION=6.0-rc1
    - VERSION=6.0-rc1-32bit
    - VERSION=6.0-rc1-32bit-buster
    - VERSION=6.0-rc1-alpine
    - VERSION=6.0-rc1-alpine3.11
    - VERSION=6.0-rc1-buster
    - VERSION=6.0-rc2
    - VERSION=6.0-rc2-alpine
    - VERSION=6.0-rc2-alpine3.11
    - VERSION=6.0-rc2-buster
    - VERSION=6.0-rc3
    - VERSION=6.0-rc3-alpine
    - VERSION=6.0-rc3-alpine3.11
    - VERSION=6.0-rc3-buster
    - VERSION=6.0-rc4
    - VERSION=6.0-rc4-alpine
    - VERSION=6.0-rc4-alpine3.11
    - VERSION=6.0-rc4-buster
    - VERSION=6.0.0
    - VERSION=6.0.0-alpine
    - VERSION=6.0.0-alpine3.11
    - VERSION=6.0.0-buster
    - VERSION=6.0.1
    - VERSION=6.0.1-alpine
    - VERSION=6.0.1-alpine3.11
    - VERSION=6.0.1-buster
    - VERSION=6.0.2
    - VERSION=6.0.2-alpine
    - VERSION=6.0.2-alpine3.11
    - VERSION=6.0.2-buster
    - VERSION=6.0.3
    - VERSION=6.0.3-alpine
    - VERSION=6.0.3-alpine3.11
    - VERSION=6.0.3-buster
    - VERSION=6.0.4
    - VERSION=6.0.4-alpine
    - VERSION=6.0.4-alpine3.11
    - VERSION=6.0.4-alpine3.12
    - VERSION=6.0.4-buster
    - VERSION=6.0.5
    - VERSION=6.0.5-alpine
    - VERSION=6.0.5-alpine3.12
    - VERSION=6.0.5-buster
    - VERSION=6.0.6
    - VERSION=6.0.6-alpine
    - VERSION=6.0.6-alpine3.12
    - VERSION=6.0.6-buster
    - VERSION=6.0.7
    - VERSION=6.0.7-alpine
    - VERSION=6.0.7-alpine3.12
    - VERSION=6.0.7-buster
    - VERSION=6.0.8
    - VERSION=6.0.8-alpine
    - VERSION=6.0.8-alpine3.12
    - VERSION=6.0.8-buster
    - VERSION=alpine
    - VERSION=alpine3.10
    - VERSION=alpine3.11
    - VERSION=alpine3.12
    - VERSION=alpine3.8
    - VERSION=alpine3.9
    - VERSION=buster
    - VERSION=latest
    - VERSION=rc
    - VERSION=rc-32bit
    - VERSION=rc-32bit-buster
    - VERSION=rc-alpine
    - VERSION=rc-alpine3.11
    - VERSION=rc-buster
    - VERSION=stretch
