language: bash
notifications:
    email: [matthew@baggett.me]
before_script:
    - 'sudo rm /usr/local/bin/docker-compose'
    - 'curl -L https://github.com/docker/compose/releases/download/1.21.0/docker-compose-`uname -s`-`uname -m` > docker-compose'
    - 'chmod +x docker-compose'
    - 'sudo mv docker-compose /usr/local/bin'
script:
    - 'docker-compose -f build.yml build redis-$VERSION'
after_script:
    - 'docker-compose -f build.yml push redis-$VERSION'
matrix:
    allow_failures: { env: [VERSION=windowsservercode, VERSION=nanoserver] }
env:
    - VERSION=windowsservercore
    - VERSION=stretch
    - VERSION=nanoserver
    - VERSION=latest
    - VERSION=buster
    - VERSION=alpine3.9
    - VERSION=alpine3.8
    - VERSION=alpine3.10
    - VERSION=alpine
    - VERSION=5.0.5-stretch
    - VERSION=5.0.5-buster
    - VERSION=5.0.5-alpine3.9
    - VERSION=5.0.5-alpine3.10
    - VERSION=5.0.5-alpine
    - VERSION=5.0.5-32bit-stretch
    - VERSION=5.0.5-32bit-buster
    - VERSION=5.0.5-32bit
    - VERSION=5.0.5
    - VERSION=5.0.4-stretch
    - VERSION=5.0.4-alpine3.9
    - VERSION=5.0.4-alpine
    - VERSION=5.0.4-32bit-stretch
    - VERSION=5.0.4-32bit
    - VERSION=5.0.4
    - VERSION=5.0.3-stretch
    - VERSION=5.0.3-alpine3.9
    - VERSION=5.0.3-alpine3.8
    - VERSION=5.0.3-alpine
    - VERSION=5.0.3-32bit-stretch
    - VERSION=5.0.3-32bit
    - VERSION=5.0.3
    - VERSION=5.0.2-stretch
    - VERSION=5.0.2-alpine3.8
    - VERSION=5.0.2-alpine
    - VERSION=5.0.2-32bit-stretch
    - VERSION=5.0.2-32bit
    - VERSION=5.0.2
    - VERSION=5.0.1-stretch
    - VERSION=5.0.1-alpine3.8
    - VERSION=5.0.1-alpine
    - VERSION=5.0.1-32bit-stretch
    - VERSION=5.0.1-32bit
    - VERSION=5.0.1
    - VERSION=5.0.0-stretch
    - VERSION=5.0.0-alpine3.8
    - VERSION=5.0.0-alpine
    - VERSION=5.0.0-32bit-stretch
    - VERSION=5.0.0-32bit
    - VERSION=5.0.0
    - VERSION=5.0-stretch
    - VERSION=5.0-rc6-stretch
    - VERSION=5.0-rc6-alpine3.8
    - VERSION=5.0-rc6-alpine
    - VERSION=5.0-rc6-32bit-stretch
    - VERSION=5.0-rc6-32bit
    - VERSION=5.0-rc6
    - VERSION=5.0-rc5-stretch
    - VERSION=5.0-rc5-alpine3.8
    - VERSION=5.0-rc5-alpine
    - VERSION=5.0-rc5-32bit-stretch
    - VERSION=5.0-rc5-32bit
    - VERSION=5.0-rc5
    - VERSION=5.0-rc4-stretch
    - VERSION=5.0-rc4-alpine3.8
    - VERSION=5.0-rc4-alpine
    - VERSION=5.0-rc4-32bit-stretch
    - VERSION=5.0-rc4-32bit
    - VERSION=5.0-rc4
    - VERSION=5.0-rc3-stretch
    - VERSION=5.0-rc3-alpine3.8
    - VERSION=5.0-rc3-alpine
    - VERSION=5.0-rc3-32bit-stretch
    - VERSION=5.0-rc3-32bit
    - VERSION=5.0-rc3
    - VERSION=5.0-rc-stretch
    - VERSION=5.0-rc-alpine3.8
    - VERSION=5.0-rc-alpine
    - VERSION=5.0-rc-32bit-stretch
    - VERSION=5.0-rc-32bit
    - VERSION=5.0-rc
    - VERSION=5.0-buster
    - VERSION=5.0-alpine3.9
    - VERSION=5.0-alpine3.8
    - VERSION=5.0-alpine3.10
    - VERSION=5.0-alpine
    - VERSION=5.0-32bit-stretch
    - VERSION=5.0-32bit-buster
    - VERSION=5.0-32bit
    - VERSION=5.0
    - VERSION=5-stretch
    - VERSION=5-buster
    - VERSION=5-alpine3.9
    - VERSION=5-alpine3.8
    - VERSION=5-alpine3.10
    - VERSION=5-alpine
    - VERSION=5-32bit-stretch
    - VERSION=5-32bit-buster
    - VERSION=5-32bit
    - VERSION=5
    - VERSION=4.0.9-alpine
    - VERSION=4.0.9-32bit
    - VERSION=4.0.9
    - VERSION=4.0.8-alpine
    - VERSION=4.0.8-32bit
    - VERSION=4.0.8
    - VERSION=4.0.7-alpine
    - VERSION=4.0.7-32bit
    - VERSION=4.0.7
    - VERSION=4.0.6-alpine
    - VERSION=4.0.6-32bit
    - VERSION=4.0.6
    - VERSION=4.0.5-alpine
    - VERSION=4.0.5-32bit
    - VERSION=4.0.5
    - VERSION=4.0.4-alpine
    - VERSION=4.0.4-32bit
    - VERSION=4.0.4
    - VERSION=4.0.2-alpine
    - VERSION=4.0.2-32bit
    - VERSION=4.0.2
    - VERSION=4.0.14-stretch
    - VERSION=4.0.14-buster
    - VERSION=4.0.14-alpine3.9
    - VERSION=4.0.14-alpine3.10
    - VERSION=4.0.14-alpine
    - VERSION=4.0.14-32bit-stretch
    - VERSION=4.0.14-32bit-buster
    - VERSION=4.0.14-32bit
    - VERSION=4.0.14
    - VERSION=4.0.13-stretch
    - VERSION=4.0.13-alpine3.9
    - VERSION=4.0.13-alpine
    - VERSION=4.0.13-32bit-stretch
    - VERSION=4.0.13-32bit
    - VERSION=4.0.13
    - VERSION=4.0.12-stretch
    - VERSION=4.0.12-alpine3.9
    - VERSION=4.0.12-alpine3.8
    - VERSION=4.0.12-alpine
    - VERSION=4.0.12-32bit-stretch
    - VERSION=4.0.12-32bit
    - VERSION=4.0.12
    - VERSION=4.0.11-stretch
    - VERSION=4.0.11-alpine3.8
    - VERSION=4.0.11-alpine
    - VERSION=4.0.11-32bit-stretch
    - VERSION=4.0.11-32bit
    - VERSION=4.0.11
    - VERSION=4.0.10-stretch
    - VERSION=4.0.10-alpine3.8
    - VERSION=4.0.10-alpine
    - VERSION=4.0.10-32bit-stretch
    - VERSION=4.0.10-32bit
    - VERSION=4.0.10
    - VERSION=4.0.1-alpine
    - VERSION=4.0.1-32bit
    - VERSION=4.0.1
    - VERSION=4.0.0-alpine
    - VERSION=4.0.0-32bit
    - VERSION=4.0.0
    - VERSION=4.0-stretch
    - VERSION=4.0-buster
    - VERSION=4.0-alpine3.9
    - VERSION=4.0-alpine3.8
    - VERSION=4.0-alpine3.10
    - VERSION=4.0-alpine
    - VERSION=4.0-32bit-stretch
    - VERSION=4.0-32bit-buster
    - VERSION=4.0-32bit
    - VERSION=4.0
    - VERSION=4-stretch
    - VERSION=4-buster
    - VERSION=4-alpine3.9
    - VERSION=4-alpine3.8
    - VERSION=4-alpine3.10
    - VERSION=4-alpine
    - VERSION=4-32bit-stretch
    - VERSION=4-32bit-buster
    - VERSION=4-32bit
    - VERSION=4
    - VERSION=32bit-stretch
    - VERSION=32bit-buster
    - VERSION=32bit
    - VERSION=3.2.9-alpine
    - VERSION=3.2.9-32bit
    - VERSION=3.2.9
    - VERSION=3.2.8-alpine
    - VERSION=3.2.8-32bit
    - VERSION=3.2.8
    - VERSION=3.2.7-alpine
    - VERSION=3.2.7-32bit
    - VERSION=3.2.7
    - VERSION=3.2.6-windowsservercore
    - VERSION=3.2.6-nanoserver
    - VERSION=3.2.6-alpine
    - VERSION=3.2.6-32bit
    - VERSION=3.2.6
    - VERSION=3.2.5-alpine
    - VERSION=3.2.5-32bit
    - VERSION=3.2.5
